In [1]:
import numpy as np
import pandas as pd
import datetime as dt

from sodapy import Socrata

In [2]:
client = Socrata("data.lacity.org", None)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [3]:
def get_results(date, client):
    results = client.get('wjz9-h9np',
                        where=f'issue_date=="{date}"',
                        limit=50000)
    results_df = pd.DataFrame.from_records(results)
    return results_df

In [4]:
past_df = pd.read_csv('../data/citations_ts.csv')

In [23]:
date = []
count = []
fines = []

i_date = dt.date(2020, 5, 1)
delta = dt.timedelta(days=1)

while i_date < dt.date.today() - delta:
    # print progression
    if i_date.day == 1:
        print(i_date)
        
    results_df = get_results(i_date, client)
    if len(results_df) > 0:
        if 'fine_amount' in results_df.columns:
            fine_total = np.sum(results_df['fine_amount'].fillna(0).astype(float))  
        else:
            fine_total = 0

        date.append(str(i_date))
        count.append(len(results_df))
        fines.append(fine_total)
    
    i_date += delta
    
df = pd.DataFrame({
    'date' : date,
    'count' : count,
    'fines' : fines
})

2020-05-01
2020-06-01
2020-07-01

In [37]:
df_a = past_df[past_df.date_a>='2020-05-01'].reset_index(drop=True)

In [35]:
past_df.columns = [c + '_a' for c in past_df.columns]

In [33]:
df.columns = [c + '_b' for c in df.columns]

In [42]:
df_b = df[df.date_b<='2020-06-26']

In [45]:
merged_df = df_a.join(df_b)

In [49]:
merged_df['count_diff'] = merged_df['count_b'] - merged_df['count_a']
merged_df['fines_diff'] = merged_df['fines_b'] - merged_df['fines_a']

In [50]:
merged_df

,date_a,count_a,fines_a,date_b,count_b,fines_b,count_diff,fines_diff
0,2020-05-01,1613,124881.0,2020-05-01,1613,124881.0,0,0.0
1,2020-05-02,1635,126955.0,2020-05-02,1635,126955.0,0,0.0
2,2020-05-03,896,75192.0,2020-05-03,896,75192.0,0,0.0
3,2020-05-04,1948,154759.0,2020-05-04,1948,154759.0,0,0.0
4,2020-05-05,1705,140129.0,2020-05-05,1705,140129.0,0,0.0
5,2020-05-06,1720,128538.0,2020-05-06,1720,128538.0,0,0.0
6,2020-05-07,1714,129430.0,2020-05-07,1714,129430.0,0,0.0
7,2020-05-08,2022,158246.0,2020-05-08,2022,158246.0,0,0.0
8,2020-05-09,1605,127307.0,2020-05-09,1605,127307.0,0,0.0
9,2020-05-10,1055,84386.0,2020-05-10,1055,84386.0,0,0.0
10,2020-05-11,2399,179285.0,2020-05-11,2399,179285.0,0,0.0
11,2020-05-12,2306,178604.0,2020-05-12,2307,178604.0,1,0.0
12,2020-05-13,2168,166389.0,2020-05-13,2168,166389.0,0,0.0
13,2020-05-14,2229,165495.0,2020-05-14,2229,165495.0,0,0.0
14,2020-05-15,2276,173276.0,2020-05-15,2276,173276.0,0,0.0
15,2020-05-16,2167,171999.0,2020-05-16,2167,171999.0,0,0.0
16,2020-05-17,1104,96444.0,2020-05-17,1104,96444.0,0,0.0
17,2020-05-18,2012,158088.0,2020-05-18,2012,158088.0,0,0.0
18,2020-05-19,2078,165681.0,2020-05-19,2079,165731.0,1,50.0
19,2020-05-20,1952,150302.0,2020-05-20,1953,150395.0,1,93.0
20,2020-05-21,2169,163149.0,2020-05-21,2170,163242.0,1,93.0
21,2020-05-22,2229,171792.0,2020-05-22,2229,171792.0,0,0.0
22,2020-05-23,2183,161529.0,2020-05-23,2183,161529.0,0,0.0
23,2020-05-24,1437,120510.0,2020-05-24,1437,120510.0,0,0.0
24,2020-05-25,1173,107093.0,2020-05-25,1173,107093.0,0,0.0
25,2020-05-26,2945,221013.0,2020-05-26,2945,221013.0,0,0.0
26,2020-05-27,2368,175458.0,2020-05-27,2372,176050.0,4,592.0
27,2020-05-28,2415,181364.0,2020-05-28,2417,181500.0,2,136.0
28,2020-05-29,2665,197170.0,2020-05-29,2665,197170.0,0,0.0
29,2020-05-30,2091,152889.0,2020-05-30,2092,152939.0,1,50.0
30,2020-05-31,474,38114.0,2020-05-31,474,38114.0,0,0.0
31,2020-06-01,1628,121594.0,2020-06-01,1632,121787.0,4,193.0
32,2020-06-02,1953,143129.0,2020-06-02,1953,143129.0,0,0.0
33,2020-06-03,126,9566.0,2020-06-03,135,10133.0,9,567.0
34,2020-06-04,2644,199772.0,2020-06-04,2659,200752.0,15,980.0
35,2020-06-05,2661,203174.0,2020-06-05,2685,205143.0,24,1969.0
36,2020-06-06,1944,147594.0,2020-06-06,1955,148482.0,11,888.0
37,2020-06-07,1159,94514.0,2020-06-07,1189,96615.0,30,2101.0
38,2020-06-08,3130,234208.0,2020-06-08,3139,234782.0,9,574.0
39,2020-06-09,3366,257814.0,2020-06-09,3371,258361.0,5,547.0
40,2020-06-10,2730,204465.0,2020-06-10,2735,204870.0,5,405.0
41,2020-06-11,3166,233927.0,2020-06-11,3170,234131.0,4,204.0
42,2020-06-12,2958,227307.0,2020-06-12,2973,228135.0,15,828.0
43,2020-06-13,2378,174953.0,2020-06-13,2414,177397.0,36,2444.0
44,2020-06-14,1228,98112.0,2020-06-14,1263,101703.0,35,3591.0
45,2020-06-15,3213,238712.0,2020-06-15,3229,239918.0,16,1206.0
46,2020-06-16,3168,236387.0,2020-06-16,3210,238572.0,42,2185.0
47,2020-06-17,3006,228319.0,2020-06-17,3053,231749.0,47,3430.0
48,2020-06-18,3051,232295.0,2020-06-18,3116,236673.0,65,4378.0
49,2020-06-19,2936,221796.0,2020-06-19,2980,225412.0,44,3616.0
50,2020-06-20,2712,197059.0,2020-06-20,2769,202047.0,57,4988.0
51,2020-06-21,1216,99502.0,2020-06-21,1299,106114.0,83,6612.0
52,2020-06-22,3247,239394.0,2020-06-22,3289,242317.0,42,2923.0
53,2020-06-23,3410,256083.0,2020-06-23,3487,261669.0,77,5586.0
54,2020-06-24,3250,248064.0,2020-06-24,3371,256715.0,121,8651.0
55,2020-06-25,3182,232457.0,2020-06-25,3298,240164.0,116,7707.0
56,2020-06-26,2982,223514.0,2020-06-26,3047,228067.0,65,4553.0